package com.ritu.eventplatform.serviceImpl;

import java.nio.charset.StandardCharsets;
import java.security.Key;
import java.util.Date;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;

import com.ritu.eventplatform.entity.User;
import com.ritu.eventplatform.service.JwtService;

import io.jsonwebtoken.Claims;
import io.jsonwebtoken.Jwts;
import io.jsonwebtoken.security.Keys;

@Service
public class JwtServiceImpl implements JwtService{
	
	//Learn @Value
	//It is used to inject values into fields in Spring-managed beans.(Ex: @Service, @Component, @Controller, etc.)
	//It can be used to inject values from property files, system properties, environment variables, or other sources.
	//Example: @Value("${jwt.secret}") private String secret; 
	// Injects the value of the "jwt.secret" property from the application.properties file into the secret field.
	// Another Example: @Value("${server.port}") private int serverPort;
	
	@Value("${jwt.secret}")
	 private String secret;
	
	@Value("${jwt.expiration}")
	private long expirationTime;

	@Override
	public String generateToken(User user) {
		
		//Key is a class in the Java Cryptography Architecture (JCA) that represents a cryptographic key. 
		//It is used for encryption, decryption, signing, and verification operations.
		// Keys.hmacShaKeyFor(byte[] keyBytes) is a method provided by the JJWT (Java JWT) library 
		//that generates a cryptographic key suitable for HMAC-SHA algorithms (e.g., HMAC-SHA256, HMAC-SHA512) based on the provided byte array.
		
		Key key = Keys.hmacShaKeyFor(secret.getBytes());
		
		// Jwts.builder() is a method provided by the JJWT (Java JWT) library that allows you to create and configure a JSON Web Token (JWT) 
		//in a fluent manner.
		// It provides a builder pattern for constructing JWTs with various claims, headers, and signing options.
		//claims are pieces of information about an entity (typically, the user) and additional metadata.
		//signWith(key) specifies the cryptographic key to sign the JWT, ensuring its integrity and authenticity.
		//compact() finalizes the JWT creation process and returns the resulting token as a compact, URL-safe string representation.
		// compact() works like this:
		// 1. Header: The header is a JSON object that typically consists of two
		// fields: "alg" (algorithm) and "typ" (type). It specifies the algorithm used for signing the token and the type of token (JWT).
		//examples: {"alg": "HS256", "typ": "JWT"}
		// 2. Payload: The payload is another JSON object that contains the claims. Claims are statements about an entity (typically, the user) and additional metadata.
		//examples: {"sub": "user123", "role": "admin", "iat": 1623456789, "exp": 1623460389}
		// 3. Signature: The signature is created by taking the encoded header, encoded payload, a secret key, and the specified algorithm.
		// It is used to verify that the sender of the JWT is who it says it is and to ensure that the message wasn't changed along the way.
		// The signature is generated by applying the specified algorithm to the concatenated header and payload, along with the secret key
		// then compact() combines the header, payload, and signature into a single string, separated by periods ('.'). 
		//The resulting string is the final JWT that can be transmitted securely between parties.
		return Jwts.builder()
				.setSubject(user.getEmail())
				.issuedAt(new Date())
				.expiration(new Date(System.currentTimeMillis() + expirationTime))
				.claim("role", user.getRole().name() )
				.signWith(key)
				.compact();
	}
	
	public Claims extractAllClaims(String token) {
		Key key = Keys.hmacShaKeyFor(secret.getBytes(StandardCharsets.UTF_8));
		
		return Jwts.parser()
				.verifyWith((javax.crypto.SecretKey)key)
				.build()
				.parseSignedClaims(token)
				.getPayload();
	}
	
	// Claims are the pieces of information about an entity (typically, the user) and additional metadata.
	// example claims: {"sub": "user123", "role": "admin", "iat": 1623456789, "exp": 1623460389}
	// 1. key represents the claim name (e.g., "sub", "role", "iat", "exp")
	//2. parser method is used to parse the JWT and extract the claims. 
	//It verifies the token's signature using the provided key and returns the claims contained in the token.
	// VerifyWith is used to specify the key that will be used to verify the JWT's signature.
	// I am using HMAC-SHA algorithm, so I need to provide a SecretKey for verification.
	// parseSignedClaims is used to parse the JWT and extract the claims. 
	//It verifies the token's signature using the provided key and returns the claims contained in the token.
	// now this claims help to find email, role etc..
	
	public String extractMail(String token) {
		return extractAllClaims(token).getSubject();
	}

	@Override
	public String extractRole(String token) {
		return extractAllClaims(token).get("role", String.class);
	}

	@Override
	public boolean isTokenValid(String token) {
		
		try {
		Claims claim = extractAllClaims(token);
		return claim.getExpiration().after(new Date()); 
	//checks if the token has expired by comparing the expiration date in the claims with the current date. 
		//If the expiration date is after the current date, it means the token is still valid; otherwise, it has expired.
		} catch (Exception e) {
			return false; // If any exception occurs during token parsing or validation, we consider the token as invalid.
		}
	}
	
	
	
	
	

}
