spring.application.name=event-platform
spring.datasource.url=jdbc:mysql://localhost:3306/event_platform
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5Dialect
spring.jpa.properties.hibernate.format_sql=true
server.port=8888
jwt.secret=ThisIsMyVerySecretKeyForJwtAuthenticationEventPlatform2026
jwt.expiration=86400000
logging.level.org.springframework.web=DEBUG
#For SMTP
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=1d50854f503a0b
spring.mail.password=bf0ced54ea1392
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
